name: J_me
description: A messaging app for J & ME.
publish_to: "none" # usipange ku-publish kwenye pub.dev

version: 1.0.0+1

environment:
  sdk: '^3.4.0'

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^3.0.3
  shared_preferences: ^2.2.2
  http: ^1.6.0
  image_picker: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

