name: j_me
description: A messaging app for J & ME.
publish_to: "none" # usipange ku-publish kwenye pub.dev

version: 1.0.0+1

environment:
  sdk: '^3.4.0'

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^3.0.3
  shared_preferences: ^2.2.2
  http: ^1.6.0
  image_picker: ^1.2.3
  emoji_picker_flutter: ^4.5.3
  flutter_local_notifications: ^13.0.0
  flutter_secure_storage: ^9.0.0
  file_picker: ^6.1.1
  email_validator: ^2.0.1
  photo_view: ^0.14.0
  phone_number: ^0.13.0
  name: ^4.3.0
  otp: ^4.2.0
  async: ^3.2.0
  device_info_plus: ^10.0.0
  lock_screen: ^2.0.0
  local_auth: ^.1.0
  audio_session: ^0.1.0
  vibration: ^1.9.0
  video_player: ^2.6.0
  camera: ^0.11.0
  microphone: ^1.0.0
  speech_to_text: ^5.0.0
  speech_to_text_platform_interface: ^5.0.0
  speaker: ^0.1.0
  remote_config: ^2.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

