"""create group_members table

Revision ID: 0319b75018fe
Revises: 3761b27de411
Create Date: 2026-07-28 16:53:16.022085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0319b75018fe'
down_revision: Union[str, Sequence[str], None] = '3761b27de411'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'user1_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('chats', 'user2_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('groups', 'admin_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('groups', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('secret_chats', 'user1_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('secret_chats', 'user2_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('secret_chats', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('secret_chats', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('secret_chats', 'user2_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('secret_chats', 'user1_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('groups', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('groups', 'admin_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('chats', 'user2_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('chats', 'user1_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
