"""add name column to chats

Revision ID: 31e9ec8ff9a4
Revises: 8f718118338d
Create Date: 2026-07-22 12:40:29.310875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31e9ec8ff9a4'
down_revision: Union[str, Sequence[str], None] = '8f718118338d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chat_members_user_id_fkey'), 'chat_members', type_='foreignkey')
    op.drop_constraint(op.f('chat_members_chat_id_fkey'), 'chat_members', type_='foreignkey')
    op.create_foreign_key(None, 'chat_members', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chat_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('chats', sa.Column('name', sa.String(), nullable=True))
    op.drop_constraint(op.f('chats_user2_id_fkey'), 'chats', type_='foreignkey')
    op.drop_constraint(op.f('chats_user1_id_fkey'), 'chats', type_='foreignkey')
    op.drop_column('chats', 'user1_id')
    op.drop_column('chats', 'user2_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('user2_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('chats', sa.Column('user1_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('chats_user1_id_fkey'), 'chats', 'users', ['user1_id'], ['id'])
    op.create_foreign_key(op.f('chats_user2_id_fkey'), 'chats', 'users', ['user2_id'], ['id'])
    op.drop_column('chats', 'name')
    op.drop_constraint(None, 'chat_members', type_='foreignkey')
    op.drop_constraint(None, 'chat_members', type_='foreignkey')
    op.create_foreign_key(op.f('chat_members_chat_id_fkey'), 'chat_members', 'chats', ['chat_id'], ['id'])
    op.create_foreign_key(op.f('chat_members_user_id_fkey'), 'chat_members', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
