"""create new tables

Revision ID: 3852bf2feb5b
Revises: a3bf4562d653
Create Date: 2026-07-29 19:14:07.695975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3852bf2feb5b'
down_revision: Union[str, Sequence[str], None] = 'a3bf4562d653'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_call_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caller_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('call_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['caller_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chat_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_call_sessions_id'), 'group_call_sessions', ['id'], unique=False)
    op.add_column('call_sessions', sa.Column('chat_id', sa.Integer(), nullable=True))
    op.alter_column('call_sessions', 'callee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'call_sessions', 'groups', ['chat_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'call_sessions', type_='foreignkey')
    op.alter_column('call_sessions', 'callee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('call_sessions', 'chat_id')
    op.drop_index(op.f('ix_group_call_sessions_id'), table_name='group_call_sessions')
    op.drop_table('group_call_sessions')
    # ### end Alembic commands ###
