"""create privacy table

Revision ID: 9b1273c91ee0
Revises: d7171f97c0b1
Create Date: 2026-07-22 11:03:33.593186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b1273c91ee0'
down_revision: Union[str, Sequence[str], None] = 'd7171f97c0b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chats', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_column('chats', 'owner_id')
    # ### end Alembic commands ###
