"""add user1_id and user2_id to chats

Revision ID: b570e6da156d
Revises: 31e9ec8ff9a4
Create Date: 2026-07-22 13:26:26.994043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b570e6da156d'
down_revision: Union[str, Sequence[str], None] = '31e9ec8ff9a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_members', sa.Column('group_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'chat_members', 'groups', ['group_id'], ['id'])
    op.add_column('chats', sa.Column('user1_id', sa.Integer(), nullable=False))
    op.add_column('chats', sa.Column('user2_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'chats', 'users', ['user2_id'], ['id'])
    op.create_foreign_key(None, 'chats', 'users', ['user1_id'], ['id'])
    op.drop_column('chats', 'name')
    op.add_column('groups', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('messages', sa.Column('group_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'messages', 'groups', ['group_id'], ['id'])
    op.alter_column("chats", "user1_id", nullable=False)
    op.alter_column("chats", "user2_id", nullable=False)
    op.alter_column("secret_chats", "user1_id", nullable=False)
    op.alter_column("secret_chats", "user2_id", nullable=False)
    op.create_unique_constraint(
        "uq_chat_users", "chats", ["user1_id", "user2_id"]
    )
    op.create_unique_constraint(
        "uq_secret_chat_users", "secret_chats", ["user1_id", "user2_id"]
    )
      # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint("uq_chat_users", "chats", type_="unique")
    op.drop_constraint("uq_secret_chat_users", "secret_chats", type_="unique")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'group_id')
    op.drop_column('groups', 'created_at')
    op.add_column('chats', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_column('chats', 'user2_id')
    op.drop_column('chats', 'user1_id')
    op.drop_constraint(None, 'chat_members', type_='foreignkey')
    op.drop_column('chat_members', 'group_id')
    op.alter_column("chats", "user1_id", nullable=False)
    op.alter_column("chats", "user2_id", nullable=False)

    # ### end Alembic commands ###

